### ISSUE TITLE
Redis Plugin Issue

### ISSUE THREAD

**Issue by ravishankara** [kenjij/newrelic_redis_plugin#8]
Trying to confifure Redis plugin, but receiving the below message -

Starting newrelic_redis_agent service...
[Tue Mar 31 09:20:46 UTC 2015] Agent Redis is at version 1.0.1
NOAUTH Authentication required.
[Tue Mar 31 09:20:46 UTC 2015] Gathered 0 statistics

How do I supply the password to the plugin?

**Comment by kenjij** [comment]
Have you tried the full URL schema in the config file?

``` yaml
agents:
  redis:
    url: redis://:p4ssw0rd@10.0.1.1:6380
```
